#!/bin/bash

# load configuration file if present
[ -f /etc/amdgpu-fancontrol.cfg ] && . /etc/amdgpu-fancontrol.cfg

HYSTERESIS="${HYSTERESIS:-6000}"      # in mK
SLEEP_INTERVAL="${SLEEP_INTERVAL:-1}" # in s

# set temps (in degrees C * 1000) and corresponding pwm values in ascending order and with the same amount of values
TEMPS="${TEMPS:-( 65000 80000 90000 )}"
PWMS="${PWMS:-( 0 153 255 )}"

HWMON="${HWMON:-"/sys/class/drm/card0/device/hwmon/hwmon0"}"
FILE_PWM="${FILE_PWM:-"$HWMON/pwm1"}"
FILE_FANMODE="${FILE_FANMODE:-"$HWMON/pwm1_enable"}"
FILE_TEMP="${FILE_TEMP:-"$HWMON/temp1_input"}"
# might want to use this later
# FILE_TEMP_CRIT="${FILE_TEMP_CRIT:-"$HWMON/temp1_crit_hyst"}"
VERBOSE="${VERBOSE:-"yes"}"

case ${VERBOSE,,} in
    'y'|'yes'|'t'|'true')
        log() {
            echo "$1"
        }
        logf() {
            format="$1"
            shift
            printf "$format" $*
        }
        ;;
    *)
        log() { :; }
        logf() { :; }
        ;;
esac

# Log the starting values for each configuration variable
log "AMDGPU-Fancontrol starting up"
log "     Hysteresis: ${HYSTERESIS:=6000} mK"  # in mK
log " Sleep Interval: ${SLEEP_INTERVAL:=1} s" # in s
logf "     Temp Steps:"
for step in ${TEMPS[@]}; do
    degree=`expr $step / 1000`
    logf " %3.0dC" $degree
done
logf "\n      PWM Steps:"
for step in ${PWMS[@]}; do
    logf "  %3.0d" $step
done
logf "\n"
log "           Path: ${HWMON:="/sys/class/drm/card0/device/hwmon/hwmon0"}"
log "       PWM File: ${FILE_PWM:="$HWMON/pwm1"}"
log "   Fanmode File: ${FILE_FANMODE:="$HWMON/pwm1_enable"}"
log "Temp Input File: ${FILE_TEMP:="$HWMON/temp1_input"}"
# might want to use this later
# log "Crit Temp File: ${FILE_TEMP_CRIT:="$HWMON/temp1_crit_hyst"}"

# check if amount of temps and pwm values match
if [ "${#TEMPS[@]}" -ne "${#PWMS[@]}" ]
then
  echo "Amount of temperature and pwm values does not match"
  exit 1
fi

# checking for privileges
if [ $UID -ne 0 ]
then
  echo "Writing to sysfs requires privileges, relaunch as root"
  exit 1
fi

# set fan mode to max(0), manual(1) or auto(2)
function set_fanmode {
  log "setting fan mode to $1"
  echo "$1" > "$FILE_FANMODE"
}

function set_pwm {
  NEW_PWM=$1
  OLD_PWM=$(cat $FILE_PWM)

  log "current pwm: $OLD_PWM, requested to set pwm to $NEW_PWM"

  if [ "$NEW_PWM" -gt "$OLD_PWM" ] || [ -z "$TEMP_AT_LAST_PWM_CHANGE" ] || [ $(($(cat $FILE_TEMP) + HYSTERESIS)) -le "$TEMP_AT_LAST_PWM_CHANGE" ]; then
    log "temp at last change was $TEMP_AT_LAST_PWM_CHANGE"
    log "changing pwm to $NEW_PWM"
    if [ "$(cat "$FILE_FANMODE")" != "1" ]; then
        log "Fan mode is not manual"
        set_fanmode 1
    fi
    echo "$NEW_PWM" > "$FILE_PWM"
    TEMP_AT_LAST_PWM_CHANGE=$(cat $FILE_TEMP)
  else
    log "not changing pwm, we just did at $TEMP_AT_LAST_PWM_CHANGE, next change when below $((TEMP_AT_LAST_PWM_CHANGE - HYSTERESIS))"
  fi
}

function interpolate_pwm {
  i=0
  TEMP=$(cat $FILE_TEMP)

  log "current temp: $TEMP"

  if [[ $TEMP -le ${TEMPS[0]} ]]; then
    # below first point in list, set to min speed
    set_pwm "${PWMS[i]}"
    return
  fi

  for i in "${!TEMPS[@]}"; do
    if [[ $i -eq $((${#TEMPS[@]}-1)) ]]; then
      # hit last point in list, set to max speed
      set_pwm "${PWMS[i]}"
      return
    elif [[ $TEMP -gt ${TEMPS[$i]} ]]; then
      continue
    fi

    # interpolate linearly
    LOWERTEMP=${TEMPS[i-1]}
    HIGHERTEMP=${TEMPS[i]}
    LOWERPWM=${PWMS[i-1]}
    HIGHERPWM=${PWMS[i]}
    PWM=$(echo "( ( $TEMP - $LOWERTEMP ) * ( $HIGHERPWM - $LOWERPWM ) / ( $HIGHERTEMP - $LOWERTEMP ) ) + $LOWERPWM" | bc)
    log "interpolated pwm value for temperature $TEMP is: $PWM"
    set_pwm "$PWM"
    return
  done
}

function reset_on_fail {
  echo "exiting, resetting fan to auto control..."
  set_fanmode 2
  exit 1
}

# always try to reset fans on exit
trap "reset_on_fail" SIGINT SIGTERM

function run_daemon {
  while :; do
    interpolate_pwm
    echo
    sleep $SLEEP_INTERVAL
  done
}

# set fan control to manual
while : ; do
    set_fanmode 1
    if [ "$(cat $FILE_FANMODE)" = "1" ]; then
        break
    fi
    log "Fanmode did not set correctly. Going to try again in a bit..."
    sleep 1
done

# finally start the loop
run_daemon

